# vim:sw=2 et ts=2

version: '3'

services:

  proxy:
    image: traefik:1.7
    networks:
      - webgateway
    environment:
      - DO_AUTH_TOKEN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme:/etc/traefik/acme
    labels:
      traefik.enable: "true"
      traefik.backend: "traefik"
      traefik.port: "8080"
      traefik.frontend.rule: "Host: traefik.iofel.me"
      traefik.frontend.auth.basic: $HTTP_AUTH
    restart: unless-stopped

  static:
    image: nginx
    networks:
      - webgateway
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.backend: "static"
      traefik.frontend.rule: "Host: iofel.me"
    restart: unless-stopped

  postgres:
    image: postgres:10-alpine
    networks:
      - database
    environment:
      - POSTGRES_USER=ben
      - POSTGRES_PASSWORD
    volumes:
      - /mnt/nextcloud-vol/postgres2:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    user: 1000:1000
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=cloud@iofel.me
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=watchtower@iofel.me
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.mailgun.org
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=cloud@iofel.me
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
    command: --monitor-only --debug

networks:
  webgateway:
    driver: bridge
  database:
    driver: bridge
