# vim:sw=2 et ts=2

version: '3'

services:

  proxy:
    image: traefik
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme:/etc/traefik/acme
    restart: unless-stopped

  static:
    image: nginx
    networks:
      - webgateway
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.backend: "static"
      traefik.frontend.rule: "Host: iofel.me"
    restart: unless-stopped

  postgres:
    image: postgres:10-alpine
    networks:
      - database
    environment:
      - POSTGRES_USER=ben
      - POSTGRES_PASSWORD
    volumes:
      - /mnt/nextcloud-vol/postgres2:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    user: 1000:1000
    restart: unless-stopped

networks:
  webgateway:
    driver: bridge
  database:
    driver: bridge
