# vim:sw=2 et ts=2

version: '3'

services:

  proxy:
    image: traefik
    networks:
      - webgateway
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme:/etc/traefik/acme
    restart: unless-stopped

  static:
    image: nginx
    networks:
      - webgateway
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.backend: static
      traefik.frontend.rule: "Host: iofel.me"
    restart: unless-stopped

networks:
  webgateway:
    driver: bridge
