# vim:sw=2 et ts=2

version: '3'

services:

  traefik:
    image: traefik:v2.2
    networks:
      - webgateway
      - monitoring_monitoring
    environment:
      - DO_AUTH_TOKEN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme:/etc/traefik/acme
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.iofel.me`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.middlewares.auth.basicauth.users: $HTTP_AUTH
      traefik.docker.network: server_webgateway
    restart: unless-stopped

  static:
    image: nginx:alpine
    networks:
      - webgateway
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.http.routers.static.rule: "Host(`iofel.me`)"
      traefik.http.routers.static.entrypoints: https
    restart: unless-stopped

  postgres:
    image: postgres:10-alpine
    networks:
      - database
    environment:
      - POSTGRES_USER=ben
      - POSTGRES_PASSWORD
    volumes:
      - /mnt/nextcloud-vol/postgres2:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    user: 1000:1000
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=cloud@iofel.me
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=watchtower@iofel.me
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.mailgun.org
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=cloud@iofel.me
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_POLL_INTERVAL=7200
    command: --debug
    restart: unless-stopped

networks:
  webgateway:
    driver: bridge
  database:
    driver: bridge
  monitoring_monitoring:
    external: true
