global:
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    forwardedHeaders:
      trustedIPs:
        - "172.16.0.0/12"
    http:
      tls:
        certResolver: leresolver
        domains:
          - main: iofel.me
            sans:
              - "*.iofel.me"
          - main: slu.gg

  synapse:
    address: :8448
    http:
      tls:
        certResolver: leresolver
        domains:
          - main: matrix.iofel.me

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

api:
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  leresolver:
    acme:
      email: letsencrypt@iofel.me
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: digitalocean

metrics:
  influxDB:
    address: influxdb:8086
    protocol: http
    database: telegraf
