debug = false
checkNewVersion = false
logLevel = "INFO"
defaultEntryPoints = ["https", "http"]
InsecureSkipVerify = true

[web] # dashboard
address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "letsencrypt@iofel.me"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
  [acme.dnsChallenge]
  provider = "digitalocean"
  [[acme.domains]]
  main = "*.iofel.me"
  sans = ["iofel.me"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "iofel.me"
exposedbydefault = false
