global:
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https

  https:
    address: :443
    http:
      tls:
        certResolver: leresolver
        domains:
          - main: iofel.me
            sans:
              - "*.iofel.me"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

api:
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  leresolver:
    acme:
      email: letsencrypt@iofel.me
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: digitalocean
