version: '3'

services:
  matrix:
    image: matrixdotorg/synapse:latest
    networks:
      - server_webgateway
      - server_database
      - default
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./matrix:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.matrix.rule: "Host(`matrix.iofel.me`)"
      traefik.http.routers.matrix.entrypoints: https,synapse
      traefik.http.services.matrix.loadbalancer.server.port: "8008"
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

  mautrix-telegram:
    image: dock.mau.dev/tulir/mautrix-telegram:latest
    restart: unless-stopped
    volumes:
      - ./telegram:/data

  mautrix-whatsapp:
    image: dock.mau.dev/tulir/mautrix-whatsapp:latest
    restart: unless-stopped
    volumes:
      - ./whatsapp:/data

  mautrix-instagram:
    image: dock.mau.dev/tulir/mautrix-instagram:latest
    restart: unless-stopped
    networks:
      - server_database
      - default
    volumes:
      - ./instagram2:/data

networks:
  server_webgateway:
    external: true
  server_database:
    external: true
