version: '3'

services:
  matrix:
    image: matrixdotorg/synapse:latest
    networks:
      - server_webgateway
      - server_database
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./matrix:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`matrix.iofel.me`)"
      traefik.http.routers.static.entrypoints: https
      traefik.docker.network: server_webgateway
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
  server_database:
    external: true
