version: '3'

services:
  matrix:
    image: matrixdotorg/synapse:latest
    networks:
      - server_webgateway
      - server_database
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ./matrix:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.matrix.rule: "Host(`matrix.iofel.me`) && Path(`/_matrix`, `/_synapse/client`)"
      traefik.http.routers.matrix.entrypoints: https,synapse
      traefik.http.services.matrix.loadbalancer.server.port: "8008"
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
  server_database:
    external: true
