# vim:sw=2 et ts=2

version: '3'

services:
  nextcloud:
    build: .
    volumes:
      - /mnt/nextcloud-vol/nextcloud:/var/www/html
    networks:
      - nextcloud
      - server_database
    labels:
      com.centurylinklabs.watchtower.enable: "false" # it's just going to fail because we build the image ourselves
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    networks:
      - nextcloud
      - server_webgateway
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/nextcloud-vol/nextcloud:/var/www/html:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.rule: "Host(`cloud.iofel.me`)"
      traefik.http.routers.nginx.entrypoints: https
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

  redis:
    image: redis:alpine
    networks:
      - nextcloud
    volumes:
      - ./redis-data:/data
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
  server_database:
    external: true
  nextcloud:
    driver: bridge
