# vim:sw=2 et ts=2

version: '3'

services:
  nextcloud:
    build: .
    volumes:
      - /mnt/nextcloud-vol/nextcloud:/var/www/html
    networks:
      - server_webgateway
      - server_database
    labels:
      traefik.enabled: true
      traefik.frontend.rule: "Host: cloud.iofel.me"
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
  server_database:
    external: true
