# vim:sw=2 et ts=2

version: '3'

services:
  nextcloud:
    build: .
    links:
      - db
    volumes:
      - /mnt/nextcloud-vol/nextcloud:/var/www/html
    networks:
      - server_webgateway
      - nextcloud
    labels:
      traefik.frontend.rule: "Host: cloud.iofel.me"
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped
  db:
    image: postgres:9-alpine
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD
    volumes:
      - /mnt/nextcloud-vol/postgres:/var/lib/postgresql/data
    networks:
      - nextcloud
    labels:
      traefik.enable: "false"
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
  nextcloud:
