# vim:sw=2 et ts=2

version: '3'

services:
  nextcloud:
    image: nextcloud
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    networks:
      - server_webgateway
      - nextcloud
    labels:
      traefik.frontend.rule: "Host: cloud.iofel.me"
    restart: unless-stopped
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - nextcloud
    labels:
      traefik.enable: "false"
    restart: unless-stopped

volumes:
  db:
  nextcloud:

networks:
  server_webgateway:
    external: true
  nextcloud:
