# vim:sw=2 et ts=2

version: '3'

services:
  unifi:
    image: linuxserver/unifi
    networks:
      - server_webgateway
    ports:
      - "3478:3478/udp"
      - "9090:8080"
    volumes:
      - ./unifi:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host: unifi.iofel.me"
      traefik.protocol: "https"
      traefik.port: "8443"
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
