# vim:sw=2 et ts=2

version: '3'

services:
  unifi:
    image: linuxserver/unifi
    networks:
      - server_webgateway
    ports:
      - "3478:3478"
      - "9090:8080"
    labels:
      traefik.frontend.rule: "Host: unifi.iofel.me"
      traefik.docker.network: "server_webgateway"
      traefik.port: "8443"
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
