# vim:sw=2 et ts=2

version: '3'

services:
  unifi:
    image: linuxserver/unifi-controller
    networks:
      - server_webgateway
    ports:
      - "3478:3478/udp"
      - "9090:8080"
    volumes:
      - ./unifi:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      traefik.enable: "true"
      traefik.http.routers.unifi.rule: "Host(`unifi.iofel.me`)"
      traefik.http.routers.unifi.entrypoints: https
      traefik.http.services.unifi.loadbalancer.server.port: "8443"
      traefik.http.services.unifi.loadbalancer.server.scheme: "https"
      com.centurylinklabs.watchtower.enable: "false"
    restart: unless-stopped

networks:
  server_webgateway:
    external: true
